unique_ids:
  assets:
    standard-page.html: KAFZU6SKZPKL3F6LRIO4N2B24R7DTQGR
    theme.css: 4JCRZJUV4V3L3QKIO564TY34RI77FDI4
  forms:
    Form1: GNP2SNWOGYRM5ICK2Q6BOI7OSHA6BL5A
  modules: {}
  scripts: {}
  server_modules: {}
